# Manage devtools and tasks with mise-en-place.
# https://mise.jdx.dev/configuration.html

min_version = "2025.8.0"

[tools]
actionlint = "1.7.7"
node = "24.7.0"
pnpm = "10.15.0"

[tasks.build]
# language=sh
run = "node ./build.js"
description = "Generates production-grade build artefacts."
alias = ["b"]

[tasks.check]
depends = ["check_actions", "check_fmt", "check_renovate"]
description = "Runs `check_actions`, `check_fmt`, and `check_renovate`."
alias = ["c"]

[tasks.check_actions]
# language=sh
run = "actionlint"
description = "Verifies the syntax of the GitHub Actions workflows with actionlint."
alias = ["ca"]

[tasks.check_fmt]
# language=sh
run = "biome check --error-on-warnings"
description = "Verifies the code style of the source code with Biome."
alias = ["cf"]

[tasks.check_renovate]
# language=sh
run = """
pnpm dlx --package renovate renovate-config-validator \
  .github/renovate.json \
  automerge-build-patch.json \
  automerge-runtime-patch.json \
  automerge-tooling-patch.json \
  default.json \
  skip-nodejs-major.json
"""
description = "Verifies the syntax of the Renovate configuration."
sources = [
	# Only run this task if `renovate.json` or a preset build artefact has changed since the last run.
	".github/renovate.json",
	"automerge-build-patch.json",
	"automerge-runtime-patch.json",
	"automerge-tooling-patch.json",
	"default.json",
	"skip-nodejs-major.json",
]
outputs = { auto = true }
alias = ["cr"]

[tasks.fmt]
# language=sh
run = "biome check --skip-parse-errors --write"
description = "Reformats the source code with Biome."
alias = ["f"]

[tasks.init]
# language=sh
run = ["pnpm install --ignore-scripts", "lefthook install"]
description = "Installs Node.js packages with pnpm and enables the Git hooks with Lefthook."
alias = ["i"]

[tasks.yolo]
# language=sh
run = "lefthook uninstall"
description = "Disables the Git hooks with Lefthook."

[env]
# Load environment variables from the `.env` and `.env.local` files.
# https://mise.jdx.dev/environments/#env-file
_.file = [".env", ".env.local"]

# Make CLI programs in `node_modules` available directly in the command line.
# https://mise.jdx.dev/mise-cookbook/nodejs.html#add-node-modules-binaries-to-the-path
_.path = ["node_modules/.bin"]

[settings]
task_output = "quiet"
